# theme = "base16_default"
theme = "kanagawa_t"

[keys.normal]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"ret" = "goto_word"
w = "move_prev_word_start"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 17 
auto-format = true
#line-number = "relative"
auto-save = true
gutters = ["diff","diagnostics", "line-numbers", "spacer", "spacer"]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
completion-timeout = 0
completion-trigger-len = 1
auto-pairs = false
bufferline = "never"
#rainbow-brackets = true

[editor.file-picker]
hidden = false
git-ignore = false
git-exclude = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
# Yazi file picker integration
E = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file",
  ":open %sh{cat /tmp/unique-file}",
  ":redraw"
]


# Git blame current line
[keys.normal.space.space]
b = """
:sh git blame -L %{cursor_line},%{cursor_line} --date=relative -- "%{buffer_name}"
"""
